Jenkinsfile update

diff --git a/Jenkinsfile10 b/Jenkinsfile10
--- a/Jenkinsfile10
+++ b/Jenkinsfile10
@@ -84,10 +84,11 @@ pipeline {
                     try {
                         echo "run-api-tests.sh.."
                         sh './run-api-tests.sh'
-                    } finally {
+                    } catch (err) {
                         //findText(textFinders: [textFinder(alsoCheckConsoleOutput: true, regexp: 'There are test failures')])
-                        findText(textFinders: [textFinder(alsoCheckConsoleOutput: true, buildResult: 'FAILURE', regexp: 'There are test failures')])
+                        //findText(textFinders: [textFinder(alsoCheckConsoleOutput: true, buildResult: 'FAILURE', regexp: 'There are test failures')])
                         //findText regexp: 'There are test failures', alsoCheckConsoleOutput: true, unstableIfFound: true allowEmptyResults: true testResults: 'target/surefire-reports/*.xml'
+                        echo "Failed: ${err}"
 
                         catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                             sh "exit 1"
@@ -103,6 +104,10 @@ pipeline {
                         //findText(textFinders: [textFinder(alsoCheckConsoleOutput: true, regexp: 'There are test failures')])
                         findText(textFinders: [textFinder(alsoCheckConsoleOutput: true, buildResult: 'FAILURE', regexp: 'There are test failures')])
                         //findText regexp: 'There are test failures', alsoCheckConsoleOutput: true, unstableIfFound: true allowEmptyResults: true testResults: 'target/surefire-reports/*.xml'
+
+                        catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
+                            sh "exit 1"
+                        }
                     }
                 }*/
 
